name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    name: Test on ubuntu-latest with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    env:
      UV_PROJECT_ENVIRONMENT: .venv
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create fresh virtual environment
        shell: bash
        run: |
          rm -rf .venv
          uv venv --python ${{ matrix.python-version }}
          uv --version

      - name: Install project and test deps
        shell: bash
        run: |
          uv pip install -e .
          uv pip install .[test]

      - name: Run tests
        shell: bash
        run: |
          uv run pytest -q


