name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install project (no extras heavy downloads)
        run: |
          uv pip install -e .
          uv pip install .[test]

      - name: Run tests
        run: |
          pytest -q
